// <auto-generated />
using System;
using ControleGastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleGastos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422163805_CriarTabelasIniciais")]
    partial class CriarTabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsFixa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ControleGastos.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bandeira")
                        .HasColumnType("text");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("ControleGastos.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("MesRef")
                        .HasColumnType("date");

                    b.Property<bool>("Paga")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ValorFixo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorSuperfluo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("ControleGastos.Models.GastoFixoCartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CartaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParcelasRestantes")
                        .HasColumnType("integer");

                    b.Property<int?>("ParcelasTotal")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.ToTable("GastosFixosCartao");
                });

            modelBuilder.Entity("ControleGastos.Models.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Prazo")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("ControleGastos.Models.MetaProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("MesRef")
                        .HasColumnType("date");

                    b.Property<int>("MetaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualAtingido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SnapshotSaldo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorAcumulado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorGuardadoMes")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("MetasProgresso");
                });

            modelBuilder.Entity("ControleGastos.Models.Projecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MediaGuardadaMes")
                        .HasColumnType("numeric");

                    b.Property<int?>("MesesNecessarios")
                        .HasColumnType("integer");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Projecao12m")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Projecao60m")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SimulacaoValorAlvo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Projecoes");
                });

            modelBuilder.Entity("ControleGastos.Models.SalarioEstimativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("MesRef")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorReal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SalariosEstimativas");
                });

            modelBuilder.Entity("ControleGastos.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsEstimativa")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("MesRef")
                        .HasColumnType("date");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ControleGastos.Models.Fatura", b =>
                {
                    b.HasOne("ControleGastos.Models.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");
                });

            modelBuilder.Entity("ControleGastos.Models.GastoFixoCartao", b =>
                {
                    b.HasOne("ControleGastos.Models.Cartao", "Cartao")
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");
                });

            modelBuilder.Entity("ControleGastos.Models.Meta", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControleGastos.Models.MetaProgresso", b =>
                {
                    b.HasOne("ControleGastos.Models.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("ControleGastos.Models.Transacao", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
